name: Anders Holden Deleuran 
description: Personal website of Anders Holden Deleuran (Design Geometer + Coder) | Senior Computational Design Specialist (BIG) | Perpetually overdue PhD fellow (CITA)
title: false
