
use_google_fonts: true # if true will use external google_fonts url below
google_fonts_url: "https://fonts.googleapis.com/css2?family=Fira+Mono&family=Montserrat:wght@400;500&family=Open+Sans:wght@300;400;500;600;700&display=swap"
use_self_hosted_fonts: false # font files must be placed in /assets/fonts folder and the @font-face definitions must be added to /assets/css/fonts.css
heading: "Montserrat"
base: "Open Sans"
monospace: "Fira Mono"
logo: "Montserrat"
